name: 🌙 Nightly Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write

jobs:
  check-commits:
    uses: daylinmorgan/actions/.github/workflows/check-commits.yml@main
    with:
      since: "24 hours"

  build-artifacts:
    needs: check-commits
    if: ${{ needs.check-commits.outputs.quit != 'true' }}
    uses: ./.github/workflows/build.yml

  create-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - run: tree artifacts

      - name: Remove Old Nightly Release
        run: |
          gh release delete nightly --yes || true
          git tag -d nightly || true
          git push origin :nightly || true

      - name: Generate New Nightly Release
        run: |
          last_tag=$(git describe --tags --abbrev=0 --match "v*.*")
          commits=$(git log $last_tag..HEAD --format="%h %s")
          cat <<EOF > notes.md
          $last_tag..nightly
          $(printf "%s" "$commits" | grep -c "^") commits since last release

          ---

          $commits
          EOF
          gh release create nightly \
            --title "Nightly Release (Pre-release)" \
            --prerelease \
            -F notes.md \
          ./artifacts/**/*

